### ISSUE TITLE
Listener crashed, waiting 2.79s (undefined method `join' for nil:NilClass)"

### ISSUE THREAD

**Issue by cdesch** [phobos/phobos#140] opened 2021-08-20 17:32 UTC
Has anyone seen this error before?
```
ERROR -- Phobos : <Hash> {:message=>"Listener crashed, waiting 2.79s (undefined method `join' for nil:NilClass)", :listener_id=>"38b19b", :retry_count=>3, :waiting_time=>2.79, :exception_class=>"NoMethodError", :exception_message=>"undefined method `join' for nil:NilClass", :backtrace=>["/usr/share/gems/gems/ruby-kafka-1.3.0/lib/kafka/fetcher.rb:69:in `stop'", "/usr/share/gems/gems/ruby-kafka-1.3.0/lib/kafka/consumer.rb:130:in `stop'", "/usr/share/gems/gems/phobos-2.1.0/lib/phobos/listener.rb:113:in `block in stop_listener'", "/usr/share/gems/gems/phobos-2.1.0/lib/phobos/instrumentation.rb:21:in `block in instrument'", "/opt/app-root/src/.gem/ruby/gems/activesupport-6.1.4/lib/active_support/notifications.rb:205:in `instrument'", "/usr/share/gems/gems/phobos-2.1.0/lib/phobos/instrumentation.rb:20:in `instrument'", "/usr/share/gems/gems/phobos-2.1.0/lib/phobos/listener.rb:110:in `stop_listener'", "/usr/share/gems/gems/phobos-2.1.0/lib/phobos/listener.rb:60:in `ensure in start'", "/usr/share/gems/gems/phobos-2.1.0/lib/phobos/listener.rb:60:in `start'", "/usr/share/gems/gems/phobos-2.1.0/lib/phobos/executor.rb:72:in `run_listener'", "/usr/share/gems/gems/phobos-2.1.0/lib/phobos/executor.rb:31:in `block (2 levels) in start'", "/opt/app-root/src/.gem/ruby/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'", "/opt/app-root/src/.gem/ruby/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'", "/opt/app-root/src/.gem/ruby/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'", "/opt/app-root/src/.gem/ruby/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'", "/opt/app-root/src/.gem/ruby/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'", "/opt/app-root/src/.gem/ruby/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'", "/usr/share/gems/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block 
in create_with_logging_context'"]}
```

**Comment by cdesch** [comment] 2021-08-20 17:34
This [issue (136)](https://github.com/phobos/phobos/issues/126) looks related

**Comment by dorner** [comment] 2021-08-20 17:50
@cdesch yes, this looks like a duplicate of #136. Is it OK if I close it? The underlying problem seems to be in the ruby-kafka library.

**Comment by cdesch** [comment] 2021-08-21 00:40
Yes. Please close. Looks like a connection error.

**Closed** 2021-08-21 23:44 UTC
